webproject/users/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for, session
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.urls import url_parse

from webproject import db
from webproject.models import Prefs, User, OAuth, GaView, Task, Notification, Url, Stats, Projects

from webproject.users.forms import (LoginForm, RegistrationForm, UpdateUserForm,
                                    DashboardSettingsForm, ResetPasswordRequestForm, ResetPasswordForm)
#  from webproject.users.picture_handler import add_profile_pic
import json

from webproject.users.ga_oauth import ga_blueprint
from webproject.users.reset_email import send_password_reset_email, send_google_oauth_reminder

from webproject.core.views import update_all_urls

# from webproject.core.general import to_datetime

from webproject.core.ga_view import tz_diff

from flask_dance.contrib.google import google

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))

    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data.lower(),
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()

        default_prefs = Prefs(user_id=user.id,
                              periods=json.dumps([7, 14, 21]),
                              timezone=str(
                                  form.timezone_hidden.data) if form.timezone_hidden.data else 'Asia/Yekaterinburg')

        default_project = Projects(name='Default project',
                                   user_id=user.id,
                                   description='My first project')

        db.session.add(default_prefs)
        db.session.add(default_project)
        db.session.commit()

        login_user(user, remember=True)

        flash('Thanks for registration!', 'info')

        return redirect(url_for('core.index'))

        #  return redirect(url_for('users.login'))

    return render_template('register.html', form=form, google=google)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))

    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data.lower()).first()

        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password', 'danger')

            return redirect(url_for('users.login'))

        login_user(user, remember=form.remember_me.data)

        next_page = request.args.get('next')

        if not next_page or not next_page[0] == '/' or url_parse(next_page).netloc != '':
            next_page = url_for('core.index')

        return redirect(next_page)

    return render_template('login.html', form=form, google=google)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


def get_profiles():
    prof_dict = {}
    for profile in current_user.gaview:
        prof_dict.setdefault(profile.username, {})
        prof_dict[profile.username].setdefault(profile.account_id, {})
        prof_dict[profile.username][profile.account_id]['account_name'] = profile.account_name
        prof_dict[profile.username][profile.account_id].setdefault('properties', {})
        prof_dict[profile.username][profile.account_id]['properties'].setdefault(profile.property_id, {})
        prof_dict[profile.username][profile.account_id]['properties'][profile.property_id][
            'property_name'] = profile.property_name
        prof_dict[profile.username][profile.account_id]['properties'][profile.property_id][
            'property_url'] = profile.url
        prof_dict[profile.username][profile.account_id]['properties'][profile.property_id].setdefault('profiles',
                                                                                                      {})
        prof_dict[profile.username][profile.account_id]['properties'][profile.property_id]['profiles'].setdefault(
            profile.profile_id, {})
        prof_dict[profile.username][profile.account_id]['properties'][profile.property_id]['profiles'][
            profile.profile_id]['profile_name'] = profile.profile_name
        prof_dict[profile.username][profile.account_id]['properties'][profile.property_id]['profiles'][
            profile.profile_id]['active'] = profile.active
    return prof_dict


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    prof_dict = get_profiles()
    profile_form = UpdateUserForm(current_user.username, current_user.email)
    dash_sett_form = DashboardSettingsForm()

    if dash_sett_form.dash_submit.data and dash_sett_form.validate():
        user_pref = Prefs.query.filter_by(user_id=current_user.id).first()
        user_pref.sorting = bool(int(dash_sett_form.sorting.data))

        period_list_row = dash_sett_form.periods.data.strip(',')
        period_list = list(int(s) for s in period_list_row.split(','))
        period_list_sorted = list(set(period_list))
        period_list_sorted = sorted(period_list_sorted)
        user_pref.periods = json.dumps(period_list_sorted)

        db.session.add(user_pref)
        db.session.commit()
        flash('Dashboard Settings Updated!', 'success')
        return redirect(url_for('users.account', _anchor='dashboard'))

    elif dash_sett_form.dash_submit.data and not dash_sett_form.validate():
        profile_form.username.data = current_user.username
        profile_form.email.data = current_user.email
        profile_form.timezone_hidden.data = current_user.pref.timezone

    elif request.method == "GET":
        dash_sett_form.periods.data = ', '.join(str(x) for x in json.loads(current_user.pref.periods))
        dash_sett_form.sorting.data = str(int(current_user.pref.sorting is True))

    if profile_form.profile_submit.data and profile_form.validate():

        # if profile_form.picture.data:
        #     username = current_user.username
        #     pic = add_profile_pic(profile_form.picture.data, username)
        #     current_user.profile_image = pic

        original_timezone = current_user.pref.timezone

        current_user.username = profile_form.username.data
        current_user.email = profile_form.email.data

        user_pref = Prefs.query.filter_by(user_id=current_user.id).first()
        user_pref.timezone = str(profile_form.timezone.data)

        db.session.add(user_pref)

        if str(profile_form.timezone.data) != original_timezone:
            if ga_blueprint.session.authorized:
                ga_views = GaView.query.filter_by(user_id=current_user.id).all()
                for view in ga_views:
                    view.time_shift = tz_diff(user_tz=str(profile_form.timezone.data), ga_tz=view.timezone)
                    db.session.add(view)
        db.session.commit()
        flash('User Account Updated!', 'success')
        return redirect(url_for('users.account', _anchor='profile'))

    elif profile_form.profile_submit.data and not profile_form.validate():
        dash_sett_form.periods.data = ', '.join(str(x) for x in json.loads(current_user.pref.periods))
        dash_sett_form.sorting.data = str(int(current_user.pref.sorting is True))
        # return redirect(url_for('users.account', _anchor='profile'))

    elif request.method == "GET":
        profile_form.username.data = current_user.username
        profile_form.email.data = current_user.email
        profile_form.timezone_hidden.data = current_user.pref.timezone

    if request.method == 'POST' and request.form.get('ga-profiles') == 'ga-profiles':
        data = request.form.to_dict()

        # Reset all active column

        reset = GaView.query.filter_by(user_id=current_user.id).all()

        for profile_entry in reset:
            profile_entry.active = False
            db.session.add(profile_entry)
        db.session.commit()

        # Delete stats from previous profiles

        del_urls = Url.query.filter_by(user_id=current_user.id).all()

        if len(del_urls) > 0:
            for url in del_urls:
                Stats.delete_url_stats(url_id=url.id)
            db.session.commit()

        # Save new active state

        for property_id, profile_id in data.items():
            if property_id != 'ga-profiles':
                entry = GaView.query.filter_by(user_id=current_user.id,
                                               property_id=property_id,
                                               profile_id=profile_id).first()
                entry.active = True
                db.session.add(entry)
        db.session.commit()

        update_all_urls()

        return redirect(url_for('users.account', _anchor='api'))

    elif request.method == 'GET':

        prof_dict = get_profiles()

    # profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_form=profile_form, dash_sett_form=dash_sett_form,
                           ga_blueprint=ga_blueprint, prof_dict=prof_dict)


@users.route('/reset-password-request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))

    form = ResetPasswordRequestForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:

            # Check if user has previously authorized with Google OAuth

            if OAuth.query.filter_by(user_id=user.id, provider='google').first():
                send_google_oauth_reminder(user)
            else:
                send_password_reset_email(user)
        flash('Check your email for the instructions to reset your password', 'info')

webproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google-site-verification" content="VMOGgKl8eszO7BtOfcMDx4t73BMbDlh9zG0mRgCCUs0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/css/bootstrap-select.min.css">
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>Track changes</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('core.index') }}">CopyTrack</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
{#            <a class="nav-item nav-link" href="{{ url_for('core.dashboard') }}">Dashboard</a>#}
            <a class="nav-item nav-link" href="{{ url_for('core.info') }}">What's new</a>
        </div>
        <div class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
            {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Sign In</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
        </div>


    </div>
</nav>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}

            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <div class="text-center">{{ message }}</div>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

{% if current_user.is_authenticated %}
    {% with tasks = current_user.get_tasks_in_progress() %}
        {% if tasks %}
            {% for task in tasks %}
                <div id="task-notification" class="alert alert-success" role="alert">
                    <div id="task-{{ task.id }}-message" class="text-center">{{ task.description }}
                        <span id="{{ task.id }}-progress">{{ task.get_progress() }}</span>%<br>
                        <a class="none-display refresh_link" href="{{ url_for('core.dashboard', project_id=session['project']) }}">Refresh the
                            dashboard page</a>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endif %}

{# Categories: success (green), info (blue), warning (yellow), danger (red) #}

<div class="container">
    {% block content %}

    {% endblock %}

</div>
<footer class="mastfoot mt-auto">
    <a class="privacy-link" href="{{ url_for('users.privacy_policy') }}">CopyTrack Privacy Policy</a>
</footer>
<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{#<script#}
{#        src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>#}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.23/moment-timezone-with-data.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/js/bootstrap-select.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/js/bootstrap4-toggle.min.js"></script>
<script>
    {#
    function set_message_count(n) {
        $('#message_count').text(n);
        $('#message_count').css('visibility', n ? 'visible' : 'hidden');
    }
     #}

    function set_task_progress(task_id, progress, failed) {
        $('#' + task_id + '-progress').text(progress);
        if (progress == 100) {
            $('.refresh_link').css('display', 'inline-block');
        }
        if (failed === 1) {
            $('#task-notification').removeClass('alert-success');
            $('#task-notification').addClass('alert-danger');
        }
    }

    function display_errors(task_id, error) {
        $('#task-' + task_id + '-message').text(error);
    }

    {% if current_user.is_authenticated %}
        $(function () {
            var since = 0;
            setInterval(function () {
                $.ajax('{{ url_for('core.notifications') }}?since=' + since).done(
                    function (notifications) {
                        for (var i = 0; i < notifications.length; i++) {
                            switch (notifications[i].name) {
                                {# case 'unread_message_count':
                                  set_message_count(notifications[i].data);
                                break; #}
                                case 'error':
                                    display_errors(notifications[i].data.task_id,
                                        notifications[i].data.message);
                                    break;
                                case 'task_progress':
                                    set_task_progress(notifications[i].data.task_id,
                                        notifications[i].data.progress,
                                        notifications[i].data.failed);
                                    break;
                            }
                            since = notifications[i].timestamp;
                        }
                    }
                );
            }, 2000);
        });
    {% endif %}
</script>

{% block js %}

{% endblock %}
</body>
</html>

webproject/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="content">
        <h1 class="mb-5">What's new in the project</h1>

        <h3>21.10.2019</h3>
        <ul class="no-style">
            <li><strong>[Changed]</strong> Update only project urls after pressing Update All button </li>
            <li><strong>[Fixed]</strong> Error message "local variable 'google_response' referenced before assignment" </li>
        </ul>

        <h3>18.10.2019</h3>
        <ul class="no-style">
            <li><strong>[Fixed]</strong> Projects could not be deleted </li>
            <li><strong>[Changed]</strong> Increased task timeout up to 600 sec (10 min) </li>
            <li><strong>[Changed]</strong> Updated dependencies </li>
        </ul>

        <h3>19.02.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Projects (add, edit, delete projects)</li>
            <li><strong>[Added]</strong> Character count for fields with text length limitations</li>
        </ul>

        <h3>03.02.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Detect user timezone during local registration (based on moment.js)</li>
            <li><strong>[Added]</strong> Universal datepicker for Add and Edit forms</li>
            <li><strong>[Added]</strong> Timezone selector in Account (based on moment.js)</li>
            <li><strong>[Changed]</strong> Internationalized datepicker and partially dashboard dates</li>
        </ul>

        <h3>29.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Edit button and edit form to every URL</li>
            <li><strong>[Changed]</strong> Every GA check will update the dashboard stats with fresh stats</li>
            <li><strong>[Changed]</strong> Updating the GA profiles will recheck stats automatically instead only
                deleting them
            </li>
            <li><strong>[Changed]</strong> Position of background jobs notifications is now after flask notifications
            </li>
            <li><strong>[Changed]</strong> Max URL length is 400 characters now</li>
            <li><strong>[Fixed]</strong> Missing trailing slash was not added automatically</li>
            <li><strong>[Fixed]</strong> Word wrap was applied to all the table</li>
        </ul>

        <h3>28.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Old URL for changed URLs</li>
            <li><strong>[Added]</strong> Description of the change</li>
            <li><strong>[Added]</strong> Old URL and description to Add URL form and dashboard</li>
            <li><strong>[Changed]</strong> Radio buttons to checkboxes for API settings</li>
            <li><strong>[Fixed]</strong> Showing stats for the same URL with different dates of change</li>
            <li><strong>[Fixed]</strong> Additional spaces at the end of the URL would prevent showing stats at all
            </li>
        </ul>

        <h3>27.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> If you add a new URL, we put the link automatically in the background job to
                check stats
            </li>
            <li><strong>[Added]</strong> Refresh icon is activated for every link</li>
            <li><strong>[Added]</strong> Icon for external link is added to every URL</li>
            <li><strong>[Added]</strong> All available Google Analytics accounts, properties and profiles
                are listed now in /account#api
            </li>
            <li><strong>[Added]</strong> If several profiles for the same URL are set in Google Analytics,
                you can select the right one in CopyTrack
            </li>
            <li><strong>[Added]</strong> User rate limitation for number of request per 100 seconds and others to
                Google API
                are handled with exponential backoff function now
            </li>
            <li><strong>[Added]</strong> Error of background jobs are shown, and colored red</li>
            <li><strong>[Added]</strong> JP non-unicode links are converted to unicode now</li>
            <li><strong>[Added]</strong> New way to check, if you have permission to check URL</li>
            <li><strong>[Added]</strong> General URL validation while adding URL</li>
            <li><strong>[Added]</strong> Integrated Sentry to catch exceptions</li>
            <li><strong>[Fixed]</strong> Publication date of some link were set wrong sometimes</li>
        </ul>

        <h3>21.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Background jobs for long backend tasks</li>
            <li><strong>[Added]</strong> Dynamic stats updating progress seen from each tab</li>
            <li><strong>[Added]</strong> Force revoke button to settings</li>
            <li><strong>[Added]</strong> More logic for missing refresh token</li>
        </ul>

        <h3>15.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Changed]</strong> Removed add and delete url forms</li>
            <li><strong>[Added]</strong> Button to delete each link separately</li>
            <li><strong>[Added]</strong> Add url button, which call the pop-up form</li>
            <li><strong>[Added]</strong> Link in the table to add or change periods</li>
        </ul>

        <h3>14.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Reset your password by email (from login screen)</li>
            <li><strong>[Added]</strong> Mail system</li>
            <li><strong>[Added]</strong> Special logic and templates to reset password for "Sign in with Google" users
            </li>
            <li><strong>[Added]</strong> Responsive emails (inc. HTML and plain text versions)</li>
        </ul>

        <h3>13.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Changed]</strong> New account menu divided by categories</li>
            <li><strong>[Changed]</strong> First column in the dashboard table is limited</li>
            <li><strong>[Changed]</strong> Table is now responsible and can be scrolled horizontally</li>
        </ul>

        <h3>11.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Changed]</strong> Website messages are colored correctly red for errors, green for success,
                blue for info
            </li>
            <li><strong>[Added]</strong> Delete all URLs button and confirmation in the settings</li>
            <li><strong>[Changed]</strong> More validation to periods, entered by user</li>
            <li><strong>[Fixed]</strong> Collisions between "Sign in with Google", if an email is already registred
            </li>
        </ul>

        <h3>09.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Sign in with Google</li>
            <li><strong>[Fixed]</strong> GA Authorization, updated OAuthlib and related packages</li>
            <li><strong>[Added]</strong> More compatibility with IE</li>
            <li><strong>[Changed]</strong> Simplified login and registration forms for IE compatibility</li>
        </ul>

        <h3>08.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Changed]</strong> New design for sign in and register forms</li>
            <li><strong>[Added]</strong> Mobile responsiveness</li>
            <li><strong>[Added]</strong> Switched to HTTP/2</li>
        </ul>

        <h3>03.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Retrieve data about Google Analytics accounts, properties and views</li>
            <li><strong>[Added]</strong> Save GA meta data inc. time zones to database</li>
            <li><strong>[Changed]</strong> Time shifting base on user time zone and GA time zone</li>
            <li><strong>[Added]</strong> Retrieve GA stats only from authorized accounts</li>
            <li><strong>[Added]</strong> Button to revoke access in account settings</li>
            <li><strong>[Added]</strong> Display user time zone in account settings</li>

        </ul>

        <h3>02.01.2019</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Authentication to access Google Analytics data made by user</li>
            <li><strong>[Added]</strong> Save access and refresh token to database</li>
            <li><strong>[Added]</strong> Link to start authentication placed in dashboard</li>
        </ul>

        <h3>28.12.2018</h3>
        <ul class="no-style">
            <li><strong>[Added]</strong> Sorting links on dashboard by the date, they were added (Account)</li>
            <li><strong>[Added]</strong> Ability to change the tracking periods (Account)</li>
            <li><strong>[Changed]</strong> Stats are retrieved only after pressing "Update All"</li>
            <li><strong>[Fixed]</strong> Positive change in bounce rate is marked in red</li>
        </ul>
    </div>
{% endblock %}

webproject/templates/login.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Sign In</h5>
                    <form class="form-signin" method="POST" novalidate>
                        {{ form.hidden_tag() }}
                        <div class="form-label-group">
                            {{ form.email(class="form-control") }}
                            {% for error in form.email.errors %}
                                <span style="color: red;">{{ error }}</span>
                            {% endfor %}
                        </div>

                        <div class="form-label-group">
                            {{ form.password(class="form-control") }}
                            {% for error in form.password.errors %}
                                <span style="color: red;">{{ error }}</span>
                            {% endfor %}
                        </div>

                        <div class="custom-control custom-checkbox mb-3">
                            {{ form.remember_me(class="custom-control-input") }}
                            {{ form.remember_me.label(class="custom-control-label") }}
                            <a href="{{ url_for('users.reset_password_request') }}" class="forgotpass">Forgot your password</a>
                        </div>
                        {{ form.submit(class="btn btn-lg btn-primary btn-block text-uppercase") }}
                        <div class="text-center mt-3">
                            <p>or <a href="{{ url_for('users.register') }}">register here</a></p>
                        </div>

                        <hr class="my-3">
                        <a class="btn btn-lg btn-google btn-block text-uppercase" href="{{ url_for('google.login') }}"
                           role="button"><i
                                class="fab fa-google mr-2"></i>Sign in with Google</a>
                        {#
                        <button class="btn btn-lg btn-facebook btn-block text-uppercase" type="submit"><i
                                class="fab fa-facebook-f mr-2"></i> Sign in with Facebook
                        </button>
                     #}
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

webproject/templates/reset_password.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Set new password</h5>
                    <form class="form-signin" method="POST" novalidate>
                        {{ form.hidden_tag() }}
                        <div class="form-label-group">
                            {{ form.password(class="form-control") }}
                            {% for error in form.password.errors %}
                                <span style="color: red;">{{ error }}</span>
                            {% endfor %}
                        </div>

                        <div class="form-label-group">
                            {{ form.pass_confirm(class="form-control") }}
                            {% for error in form.pass_confirm.errors %}
                                <span style="color: red;">{{ error }}</span>
                            {% endfor %}
                        </div>
                        {{ form.submit(class="btn btn-lg btn-danger btn-block text-uppercase") }}

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

webproject/templates/reset_password_request.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Reset password</h5>
                    <form class="form-signin" method="POST" novalidate>
                        {{ form.hidden_tag() }}
                        <div class="form-label-group">
                            {{ form.email(class="form-control") }}
                            {% for error in form.email.errors %}
                                <span style="color: red;">{{ error }}</span>
                            {% endfor %}
                        </div>
                        {{ form.submit(class="btn btn-lg btn-danger btn-block text-uppercase") }}
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}